### ISSUE TITLE
Groovydoc 2.5.0: groovy.lang.MissingMethodException: No signature of method: java.util.Date.format() is applicable for argument types: (String) values: [yyyy-MM-dd]

### ISSUE THREAD

**Issue by zman0900** [groovy/GMavenPlus#100]
With groovy 2.5.0 and groovy-groovydoc 2.5.0 on the compile classpath, and the following execution of GMavenPlus 1.6:

```xml
<execution>
    <id>gdoc-jar-prepare</id>
    <phase>prepare-package</phase>
    <goals>
        <goal>groovydoc</goal>
    </goals>
    <configuration>
        <groovyDocOutputDirectory>${project.build.directory}/gapidocs</groovyDocOutputDirectory>
    </configuration>
</execution>
```
I get the following error printed many times for every groovy file:

```
Error processing class template for: <class name here>
groovy.lang.MissingMethodException: No signature of method: java.util.Date.format() is applicable for argument types: (String) values: [yyyy-MM-dd]
Possible solutions: from(java.time.Instant), toYear(), getAt(java.lang.String), parse(java.lang.String), print(java.lang.Object), print(java.io.PrintWriter)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at groovy.tmp.templates.GStringTemplateScript11$_getTemplate_closure1.doCall(GStringTemplateScript11.groovy:97)
	at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at groovy.lang.Closure$WritableClosure.writeTo(Closure.java:861)
	at org.codehaus.groovy.tools.groovydoc.GroovyDocTemplateEngine.applyClassTemplates(GroovyDocTemplateEngine.java:89)
	at org.codehaus.groovy.tools.groovydoc.GroovyDocWriter.writeClassToOutput(GroovyDocWriter.java:59)
	at org.codehaus.groovy.tools.groovydoc.GroovyDocWriter.writeClasses(GroovyDocWriter.java:50)
	at org.codehaus.groovy.tools.groovydoc.GroovyDocTool.renderToOutput(GroovyDocTool.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.gmavenplus.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:275)
	at org.codehaus.gmavenplus.mojo.AbstractGroovyDocMojo.generateGroovyDoc(AbstractGroovyDocMojo.java:432)
	at org.codehaus.gmavenplus.mojo.AbstractGroovyDocMojo.doGroovyDocGeneration(AbstractGroovyDocMojo.java:245)
	at org.codehaus.gmavenplus.mojo.GroovyDocMojo.execute(GroovyDocMojo.java:47)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Some of the errors just start with `Error processing root doc template` but otherwise have the same stack trace.

The generated groovydoc appears to have a valid index, **but the html files for each class are just zero byte files**.  This also happens if I include groovy-all instead of just groovy-groovydoc.  This all worked fine previously with Groovy 2.4.15.

Generating the groovydoc manually seems to work OK using a command like this:

    GROOVY_HOME=~/Downloads/groovy-2.5.0 PATH="${GROOVY_HOME}/bin:${PATH}" groovydoc -d gdoc --debug -sourcepath /path/to/src/main/groovy/ my.package *.groovy

This does not work recursively, but the few files it does pick up look correct.  So it seems to me that something is not right in GMavenPlus.

Maven version: 3.5.3
Java version: 1.8.0_172
OS: MacOS 10.13.5

**Comment by zman0900** [comment]
Tried this again with GMavenPlus 1.6.1 and the problem still exists.

Also, whatever is happening here does not happen with Groovy 3.0.0-alpha-2.  Doc builds with no warnings and doesn't appear to be missing any content.

**Comment by zman0900** [comment]
Even stranger, the groovydocTests goal does not seem to have this problem with Groovy 2.5.0.  So there is either some key difference between the two goals, or this bug is being triggered by something within my code itself.

**Comment by keeganwitt** [comment]
The code is actually the same for the tests and main code in GMavenPlus.  I believe this is coming from the Groovy code in the [templates](https://github.com/apache/groovy/tree/master/subprojects/groovy-groovydoc/src/main/resources/org/codehaus/groovy/tools/groovydoc/gstringTemplates).  I'm not sure why yet though -- that method is still totally available in 2.5.0.

**Comment by keeganwitt** [comment]
One thing I'll have fixed in the next release is the path to the ico file has changed.  I'm still trying to figure out what changed with 2.5.0.

**Comment by keeganwitt** [comment]
Are you depending on the groovy-all pom?  Or just groovy?

What I saw is that groovy-groovydoc has a runtime, not a compile dependency on groovy-dateutil, so it's not put in the classpath for GMavenPlus since it only adds compile dependencies.  So I've either got to add runtime dependencies in GMavenPlus or change Groovy to make it a compile rather than a runtime dependency.

For now, you should be able to add like
```xml
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-dateutil</artifactId>
            <version>2.5.0</version>
            <classifier>indy</classifier>
        </dependency>
```
as a project dependency.

**Comment by zman0900** [comment]
I tried both groovy-all and groovy + groovy-groovydoc as my dependencies and had the same results.  With an explicit compile scope dependency on groovy-dateutil, groovydoc is working again.  

First bullet of [breaking changes](http://groovy-lang.org/releasenotes/groovy-2.5.html#Groovy2.5releasenotes-Breakingchanges) in the release notes does actually mention this:  

```
The extension methods for the java.util.Date class are now in a separate groovy-dateutil module which isn’t included by default when using the groovy-all pom dependency. Add the additional module as a dependency if you need it or consider migrating to the java.time JSR-310 classes (similar Groovy extension methods exist for those classes and they are included by default when using the groovy-all pom dependency).
```

Although it seems very strange that groovydocTests was no affected, and the problem doesn't happen with the pre-release 3.0 version.

**Comment by keeganwitt** [comment]
The groovydoc tests aren't affected because that mojo brings in Maven's test scoped dependencies (which is compile + runtime + test).  Whereas normal groovydoc was just compile and not runtime.

**Comment by keeganwitt** [comment]
I forgot to include the issue number in my commit.  9d7de399ab6cc4599ca7b0e11e9a0f5157ad2cbc fixes this.
