### ISSUE TITLE
`NullPointerException` from `ClassWrangler.getGroovyVersionString`

### ISSUE THREAD

**Issue by jglick** [groovy/GMavenPlus#210]
```
Unable to get Groovy version from GroovySystem, trying InvokerHelper.
[WARN] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
Unable to determine Groovy version. Is Groovy declared as a dependency?
…
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.13.1:execute (…) on project …: Execution … of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.13.1:execute failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:274)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:196)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution … of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.13.1:execute failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:271)
	... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.codehaus.gmavenplus.util.ClassWrangler.getGroovyVersionString(ClassWrangler.java:121)
	at org.codehaus.gmavenplus.util.ClassWrangler.logGroovyVersion(ClassWrangler.java:224)
	at org.codehaus.gmavenplus.mojo.ExecuteMojo.doExecute(ExecuteMojo.java:118)
	at org.codehaus.gmavenplus.mojo.ExecuteMojo.execute(ExecuteMojo.java:90)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 12 common frames omitted
```

https://github.com/groovy/GMavenPlus/blob/eb7f459d6410f36163ed6e9aa8fe41b18a31c473/src/main/java/org/codehaus/gmavenplus/util/ClassWrangler.java#L121 seems to fail to account for a null return value from `getGroovyJar`.

**Comment by keeganwitt** [comment]
I think that stacktrace only shows up when you are using a commandline switch such as debug (`-X`). But you're right, the message could be cleaned up.

**Comment by jglick** [comment]
> a commandline switch such as debug (`-X`)

`-e` rather. If you do not, it is worse: you see that the mojo failed but you only see that there is a `NullPointerException` with no idea why.
