### ISSUE TITLE
Unable to use groovy script execution with maven -T switch.

### ISSUE THREAD

**Issue by glianeric** [groovy/GMavenPlus#56]
I have defined a script in a top level pom which sets certain file paths.
The project itself is fairly large with a lot of sub-modules, and it benefits from running multi-threaded.

However, both gmaven and gmavenplus run into this problem when running multi-threaded:

java.lang.SecurityException: Use of System.exit() is forbidden!
        at org.codehaus.gmavenplus.util.NoExitSecurityManager.checkExit(NoExitSecurityManager.java:69)
        at java.lang.Runtime.exit(Runtime.java:107)
        at java.lang.System.exit(System.java:971)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
Exception in thread "main" java.lang.SecurityException: Use of System.exit() is forbidden!
        at org.codehaus.gmavenplus.util.NoExitSecurityManager.checkExit(NoExitSecurityManager.java:69)
        at java.lang.Runtime.exit(Runtime.java:107)
        at java.lang.System.exit(System.java:971)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:364)

Is it possible to fix this?   This is the same problem as GMAVEN-114 and GMAVENPLUS-34.

Although the ticket indicates that this was fixed in 1.4, I am still running into this problem.

**Comment by glianeric** [comment]
After looking at the source, I see that I can declare allowSystemExits to true.   My apologies for the trouble!

**Comment by keeganwitt** [comment]
No worries, glad you found what you needed :smile:
