### ISSUE TITLE
groovydoc failure after upgrade to 1.6

### ISSUE THREAD

**Issue by zman0900** [groovy/GMavenPlus#85]
After upgrading to GMavenPlus 1.6, groovydoc goal failed.  Project is mixed java and groovy.  This is the execution:

    <execution>
        <id>gdoc-jar-prepare</id>
        <phase>prepare-package</phase>
        <goals>
            <goal>groovydoc</goal>
        </goals>
        <configuration>
            <groovydocJavaSources>false</groovydocJavaSources>
            <groovydocOutputDirectory>${project.build.directory}/gapidocs</groovydocOutputDirectory>
        </configuration>
    </execution>

Running maven with debug enabled shows that there is a missing class: `org.fusesource.jansi.AnsiRenderWriter`

    [ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:groovydoc (gdoc-jar-prepare) on project <redacted>: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: org/fusesource/jansi/AnsiRenderWriter: org.fusesource.jansi.AnsiRenderWriter -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:groovydoc (gdoc-jar-prepare) on project <redacted>: Error occurred while calling a method on a Groovy class from classpath.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: org.apache.maven.plugin.MojoExecutionException: Error occurred while calling a method on a Groovy class from classpath.
        at org.codehaus.gmavenplus.mojo.GroovyDocMojo.execute(GroovyDocMojo.java:51)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 11 more
    Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.gmavenplus.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:275)
        at org.codehaus.gmavenplus.mojo.AbstractGroovyDocMojo.generateGroovyDoc(AbstractGroovyDocMojo.java:425)
        at org.codehaus.gmavenplus.mojo.AbstractGroovyDocMojo.doGroovyDocGeneration(AbstractGroovyDocMojo.java:245)
        at org.codehaus.gmavenplus.mojo.GroovyDocMojo.execute(GroovyDocMojo.java:47)
        ... 13 more
    Caused by: java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiRenderWriter
        at org.codehaus.groovy.tools.shell.util.Logger.log(Logger.java:49)
        at org.codehaus.groovy.tools.shell.util.Logger.error(Logger.java:115)
        at org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder.processFile(GroovyRootDocBuilder.java:231)
        at org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder.buildTree(GroovyRootDocBuilder.java:174)
        at org.codehaus.groovy.tools.groovydoc.GroovyDocTool.add(GroovyDocTool.java:82)
        ... 21 more
    Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiRenderWriter
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 26 more
    [ERROR]

Also, in the debug log above here, after "Adding sources to generate GroovyDoc for:", many of my Java sources are listed, so it seems that the groovydocJavaSources=false setting might be ignored also.

More info:
OS: MacOS 10.12.6
Maven: 3.5.0
Java: 1.7

**Comment by zman0900** [comment]
I've tried disabling maven's color output by running with -B, and I've also tried adding `org.fusesource.jansi:jansi:1.16` as a dependency to the plugin both in the plugins section and in pluginManagement, but still get the same error.

Also, when I run without debugging, I see the following output:

    [INFO] --- gmavenplus-plugin:1.6:groovydoc (gdoc-jar-prepare) @ <redacted> ---
    [INFO] Using Groovy 2.4.12 to perform groovydoc.
    line 121:17: expecting LCURLY, found '('
    line 123:28: unexpected token: FileStatus
    line 125:31: unexpected token: Path

**Comment by keeganwitt** [comment]
The only Jansi requirement I know if is for Groovysh, there should be no dependency for Groovydoc.  The second error you mention sounds like the Groovydoc parser was choking on one of the classes.

This works fine with 1.5?

**Comment by zman0900** [comment]
Yeah, no problems on 1.5.

**Comment by keeganwitt** [comment]
Side note: I realized I changed the casing of `groovydocJavaSources` to `groovyDocJavaSources` when I was trying to make the casing consistent, which I hadn't documented.

Do you have a small project in which this can be reproduced?  I have multiple tests for GroovyDoc, there must be something you're doing differently that I haven't tested.  Sorry for the bother, I'm just a bit at a loss to understand what's going on here.
Groovy's GroovyDocTool is using Jansi, but it's been that way for quite a while now, and I haven't changed the Jansi version or the classpath used by the GroovyDoc mojo.  Quite puzzling.

**Comment by keeganwitt** [comment]
I'm still having trouble reproducing this.  Are there any dependencies in your project bringing in jansi transitively?

**Comment by zman0900** [comment]
I finally revisited this issue months later, and it seems the issue was caused by using the wrong case for one of the configuration options.  With that corrected, groovydoc seems to work as expected with 1.6.

**Comment by ringerc** [comment]
FWIW, I've hit nearly the same error by trying to run `groovydoc` on a file named `Jenkinsfile` (no extension). Renaming it to `Jenkinsfile.groovy` allowed groovydoc to succeed.
